# Generated by Django 5.2.7 on 2025-12-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Events - Event', 'verbose_name_plural': 'Events - Events'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['name'], 'verbose_name': 'Events - Category', 'verbose_name_plural': 'Events - Categories'},
        ),
        migrations.AlterModelOptions(
            name='eventinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Events - Inquiry', 'verbose_name_plural': 'Events - Inquiries'},
        ),
    ]
