# Generated by Django 5.2.7 on 2026-04-26 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='featured_image'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
    ]
