# Generated by Django 5.2.7 on 2026-05-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. VIP, Single, Couple, At the Gate, Early Bird', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES. Use 0 for free tickets.', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Brief description of what this ticket includes', max_length=200)),
                ('available', models.PositiveIntegerField(default=0, help_text='Number of tickets currently available')),
                ('total', models.PositiveIntegerField(default=0, help_text='Total tickets in this category')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event')),
            ],
            options={
                'verbose_name': 'Events - Ticket Category',
                'verbose_name_plural': 'Events - Ticket Categories',
                'ordering': ['order', 'price'],
            },
        ),
    ]
