# Generated by Django 5.2.7 on 2026-05-03 14:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_ticket_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account_name',
            field=models.CharField(default='The Misscomm Events', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='account_number',
            field=models.CharField(default='0310848627615', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='paybill_number',
            field=models.CharField(default='542542', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till_number', 'Till Number'), ('both', 'Both')], default='paybill', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='result_visibility',
            field=models.CharField(choices=[('full_live', 'Full Live Totals'), ('rankings_only', 'Rankings Only'), ('hidden', 'Hidden Totals'), ('no_public', 'No Public Updates')], default='full_live', help_text='What the public sees for vote results', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_prefix',
            field=models.CharField(blank=True, help_text='Auto-derived from event title. 2-3 char prefix for ticket codes (e.g. FOS)', max_length=5),
        ),
        migrations.AddField(
            model_name='event',
            name='till_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Price per vote in KES (e.g. 10.00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_enabled',
            field=models.BooleanField(default=False, help_text='Enable voting for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_end',
            field=models.DateTimeField(blank=True, help_text='When voting closes', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_start',
            field=models.DateTimeField(blank=True, help_text='When voting opens', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vote_reversal', 'Vote Reversal'), ('contestant_edit', 'Contestant Edit'), ('event_setting_change', 'Event Setting Change'), ('payment_adjustment', 'Payment Adjustment'), ('payment_verified', 'Payment Verified'), ('ticket_issued', 'Ticket Issued'), ('admin_action', 'Admin Action')], max_length=30)),
                ('actor', models.CharField(help_text="Admin username or 'system'", max_length=150)),
                ('details', models.TextField(help_text='JSON-serializable description of the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='events.event')),
            ],
            options={
                'verbose_name': 'Events - Audit Log',
                'verbose_name_plural': 'Events - Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('contestant_number', models.PositiveIntegerField(help_text='Display number shown to voters')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for public page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='events.event')),
            ],
            options={
                'verbose_name': 'Events - Contestant',
                'verbose_name_plural': 'Events - Contestants',
                'ordering': ['contestant_number'],
                'unique_together': {('event', 'contestant_number'), ('event', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('mpesa_code', models.CharField(help_text='M-Pesa transaction code (must be unique)', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('ticket', 'Ticket'), ('vote', 'Vote')], max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.event')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Events - Payment',
                'verbose_name_plural': 'Events - Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(help_text='Format: PREFIX-RAND4#YY (e.g. FOS-WER3#26)', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Scanned at gate')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.payment')),
                ('ticket_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.ticketcategory')),
            ],
            options={
                'verbose_name': 'Events - Ticket',
                'verbose_name_plural': 'Events - Tickets',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField(help_text='Calculated: payment amount / vote_price (backend-only)')),
                ('phone_number', models.CharField(max_length=20)),
                ('mpesa_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='events.contestant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='events.event')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='events.payment')),
            ],
            options={
                'verbose_name': 'Events - Vote Transaction',
                'verbose_name_plural': 'Events - Vote Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
