# Generated by Django 5.2.7 on 2026-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_account_name_event_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code (must be unique). Leave blank for pending payments.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='votetransaction',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=20),
        ),
    ]
