# Generated by Django 5.2.7 on 2026-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_payment_mpesa_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Daraja CheckoutRequestID from STK Push', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='Daraja MerchantRequestID from STK Push', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='stk_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw STK Push response/callback data for debugging'),
        ),
    ]
