# Generated by Django 5.2.7 on 2026-05-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contestant',
            field=models.ForeignKey(blank=True, help_text='Contestant being voted for (for vote payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.contestant'),
        ),
    ]
