# Generated by Django 5.2.7 on 2026-05-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_payment_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.ticketcategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]

