# Generated by Django 5.2.7 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_payment_ticket_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

