# Generated by Django 5.2.7 on 2026-05-07 00:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_payment_ticket_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_speakers', to='events.event')),
            ],
            options={
                'verbose_name': 'Events - Guest Speaker',
                'verbose_name_plural': 'Events - Guest Speakers',
                'ordering': ['order', 'name'],
            },
        ),
    ]

