# Generated by Django 5.2.7 on 2026-05-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_guest_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_categories', to='events.event')),
            ],
            options={
                'verbose_name': 'Events - Contestant Category',
                'verbose_name_plural': 'Events - Contestant Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestants', to='events.contestantcategory'),
        ),
    ]

