# Generated by Django 5.2.7 on 2026-05-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_contestant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='achievements',
            field=models.TextField(blank=True, help_text='Previous awards or accomplishments'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='beliefs',
            field=models.TextField(blank=True, help_text='Personal beliefs or values'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='mission_statement',
            field=models.TextField(blank=True, help_text='What they hope to achieve as Miss Culture'),
        ),
    ]
