# Generated by Django 5.2.7 on 2026-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_contestant_achievements_contestant_beliefs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='till_number',
            field=models.CharField(default='4766976', max_length=20),
        ),
    ]
