# Generated by Django 5.2.7 on 2026-05-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_till_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_method',
            field=models.CharField(choices=[('till_number', 'Till Number')], default='till_number', max_length=20),
        ),
    ]
