# Generated by Django 5.2.7 on 2026-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_contribution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_pin',
            field=models.CharField(blank=True, help_text="PIN staff enter on the /checkin page to view and check in this event's tickets. Leave blank to disable check-in for this event.", max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('vote', 'Vote'), ('donation', 'Donation')], help_text='Purpose of this payment: ticket, vote, or donation', max_length=10),
        ),
    ]
