# Generated by Django 5.2.7 on 2026-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_checkin_pin_alter_payment_payment_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, help_text='PIN staff enter on the /finance page to view revenue (voting, ticketing, contributions) and download statements. Leave blank to disable the finance page.', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Events - Finance Settings',
                'verbose_name_plural': 'Events - Finance Settings',
            },
        ),
    ]
