web: gunicorn missculture.wsgi:application --bind 0.0.0.0:$PORT --workers 5 --threads 4 --worker-class gthread --log-file - --timeout 45 --graceful-timeout 30
worker: python manage.py rqworker default
