# Generated by Django 5.2.7 on 2025-12-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery - Photo', 'verbose_name_plural': 'Gallery - Photos'},
        ),
        migrations.AlterModelOptions(
            name='photocollection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery - Photo Collection', 'verbose_name_plural': 'Gallery - Photo Collections'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery - Video', 'verbose_name_plural': 'Gallery - Videos'},
        ),
    ]
