# Generated by Django 5.2.7 on 2026-04-26 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_options_alter_photocollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='photocollection',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_file'),
        ),
    ]
