# Generated by Django 5.2.7 on 2026-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerysettings_hero_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or other external video link. If provided, this takes priority over uploaded video_file.'),
        ),
    ]
