# Generated by Django 5.2.7 on 2025-12-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Global Stage - Achievement', 'verbose_name_plural': 'Global Stage - Achievements'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog - Latest Insights', 'verbose_name_plural': 'Blog - Latest Insights'},
        ),
        migrations.AlterModelOptions(
            name='culturalcommunity',
            options={'verbose_name': 'Our Culture - Community', 'verbose_name_plural': 'Our Culture - Communities'},
        ),
        migrations.AlterModelOptions(
            name='culturalheritage',
            options={'verbose_name': 'Our Culture - Heritage Site', 'verbose_name_plural': 'Our Culture - Heritage Sites'},
        ),
        migrations.AlterModelOptions(
            name='kenyaregion',
            options={'verbose_name': 'Our Kenya - Region', 'verbose_name_plural': 'Our Kenya - Regions'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partnership - Partner/Sponsor', 'verbose_name_plural': 'Partnership - Partners/Sponsors'},
        ),
    ]
