# Generated by Django 5.2.7 on 2026-04-26 17:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_achievement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='home_hero')),
                ('kenya_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kenya_hero')),
                ('ambassador_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ambassador_hero')),
                ('events_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='events_hero')),
                ('gallery_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery_hero')),
                ('voting_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_hero')),
                ('partnership_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='partnership_hero')),
                ('contribute_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='contribute_hero')),
                ('contact_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='contact_hero')),
                ('faq_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='faq_hero')),
                ('about_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_hero')),
                ('about_mission_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_mission')),
                ('privacy_hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='privacy_hero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
