# Generated by Django 5.2.7 on 2026-04-28 20:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_leader_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_leader_1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_leader_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_leader_2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_leader_3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_leader_3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ambassador_profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ambassador_profile'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ambassador_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='ambassador_video_url'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_ambassador_highlight_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='home_ambassador_highlight'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='home_hero_video_url'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_kenya_highlight_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='home_kenya_highlight'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_upcoming_event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='home_upcoming_event'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kenya_artisan_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kenya_artisan_1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kenya_artisan_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kenya_artisan_2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kenya_artisan_3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kenya_artisan_3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kenya_artisan_4_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kenya_artisan_4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_event_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_event_1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_event_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_event_2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_event_3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_event_3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_event_4_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_event_4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_4_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_5_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_5'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='voting_participant_6_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='voting_participant_6'),
        ),
    ]
