# Generated by Django 5.2.7 on 2026-05-01 11:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings_committee_1_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='Role or title (e.g. Miss Culture Global Kenya, Director of Operations)', max_length=200)),
                ('role', models.CharField(blank=True, help_text='Committee role (only for committee members)', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('team_type', models.CharField(choices=[('leadership', 'Leadership'), ('committee', 'Organizing Committee')], default='leadership', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = shown first)')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About - Team Member',
                'verbose_name_plural': 'About - Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X'), ('tiktok', 'TikTok')], max_length=50),
        ),
    ]
