# Generated by Django 5.2.7 on 2026-05-01 13:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalheritage',
            name='video_clip',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_clip'),
        ),
        migrations.AddField(
            model_name='culturalheritage',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, etc.) — overrides uploaded video clip', verbose_name='video_url'),
        ),
    ]
