# Generated by Django 5.2.7 on 2026-05-10 06:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_logos_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mpesa_logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='M-Pesa logo for payment sections', max_length=255, null=True, verbose_name='mpesa_logo'),
        ),
    ]
