# Generated by Django 5.2.7 on 2026-05-10 13:53

import cloudinary.models
from django.db import migrations, models


def safe_remove_columns(apps, schema_editor):
    """Safely remove columns that may or may not exist in production"""
    if schema_editor.connection.vendor == 'postgresql':
        columns_to_remove = [
            'home_ambassador_highlight_image',
            'home_kenya_highlight_image',
            'home_upcoming_event_image',
            'kenya_artisan_1_image',
            'kenya_artisan_2_image',
            'kenya_artisan_3_image',
            'kenya_artisan_4_image',
        ]
        for col in columns_to_remove:
            schema_editor.execute(
                f'ALTER TABLE main_sitesettings DROP COLUMN IF EXISTS "{col}";'
            )
    else:
        # SQLite doesn't support DROP COLUMN IF EXISTS easily, skip
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_homepagesettings_recent_event_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambassador',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ambassador', 'verbose_name_plural': 'Ambassador'},
        ),
        migrations.RunPython(safe_remove_columns, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ambassadorpagesettings',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile image for ambassador (also used on homepage spotlight)', max_length=255, null=True, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='ambassadorpagesettings',
            name='video_url',
            field=models.URLField(blank=True, help_text='Featured video URL for ambassador page', null=True, verbose_name='video_url'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='ambassador_highlight_enabled',
            field=models.BooleanField(default=True, help_text='Show Ambassador spotlight section on homepage'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='ambassador_highlight_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image for Ambassador highlight card on homepage', max_length=255, null=True, verbose_name='ambassador_highlight'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='kenya_highlight_enabled',
            field=models.BooleanField(default=True, help_text='Show Kenya highlight section on homepage'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='kenya_highlight_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image for Kenya highlight card on homepage', max_length=255, null=True, verbose_name='kenya_highlight'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='upcoming_event_enabled',
            field=models.BooleanField(default=True, help_text='Show upcoming events section on homepage'),
        ),
    ]
