# Generated by Django 5.2.7 on 2026-05-11 17:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_ambassador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero')),
                ('page_title', models.CharField(default='Contribute', max_length=200)),
                ('page_subtitle', models.TextField(blank=True, default='Support our mission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contribute Page Settings',
                'verbose_name_plural': 'Contribute Page Settings',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero')),
                ('page_title', models.CharField(default='Privacy Policy', max_length=200)),
                ('page_subtitle', models.TextField(blank=True, default='Your privacy matters to us')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Page Settings',
                'verbose_name_plural': 'Privacy Page Settings',
            },
        ),
        migrations.CreateModel(
            name='TermsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero')),
                ('page_title', models.CharField(default='Terms of Service', max_length=200)),
                ('page_subtitle', models.TextField(blank=True, default='Terms and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms Page Settings',
                'verbose_name_plural': 'Terms Page Settings',
            },
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_video_url',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='welcome_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='welcome_title',
        ),
        # NOTE: Migration 0016 already dropped these 7 columns at the DB level via
        # RunPython(safe_remove_columns) using DROP COLUMN IF EXISTS.
        # We only need to sync Django's migration state here - issuing another
        # DDL DROP would fail on Postgres with UndefinedColumn. So we use
        # SeparateDatabaseAndState with database_operations=[] (no-op on DB).
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='home_ambassador_highlight_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='home_kenya_highlight_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='home_upcoming_event_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='kenya_artisan_1_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='kenya_artisan_2_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='kenya_artisan_3_image',
                ),
                migrations.RemoveField(
                    model_name='sitesettings',
                    name='kenya_artisan_4_image',
                ),
            ],
        ),
    ]
