# Generated by Django 5.2.7 on 2026-05-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_socialmediapost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-featured', '-year', 'title'], 'verbose_name': 'Kenya - Achievement', 'verbose_name_plural': 'Kenya - Achievements'},
        ),
        migrations.AlterModelOptions(
            name='culturalcommunity',
            options={'ordering': ['-featured', 'name'], 'verbose_name': 'Kenya - Community', 'verbose_name_plural': 'Kenya - Communities'},
        ),
        migrations.AlterModelOptions(
            name='culturalheritage',
            options={'ordering': ['-featured', 'title'], 'verbose_name': 'Kenya - Heritage', 'verbose_name_plural': 'Kenya - Heritage'},
        ),
        migrations.AlterModelOptions(
            name='kenyaregion',
            options={'ordering': ['-featured', 'name'], 'verbose_name': 'Kenya - Region', 'verbose_name_plural': 'Kenya - Regions'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Partnership - Partner/Sponsor', 'verbose_name_plural': 'Partnership - Partners/Sponsors'},
        ),
    ]
