# Generated by Django 5.2.7 on 2026-05-20 16:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_4_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_4_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='leader_4'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_4_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_4_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_5_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_5_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='leader_5'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_5_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_5_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_6_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_6_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='leader_6'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_6_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='leader_6_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
